### ISSUE TITLE
License

### ISSUE THREAD

**Issue by fommil** [gkossakowski/kentuckymule#1]
Please include a license so that people can use, build on, or even look at, your work.

I recommend any libre software license compatible with the gpl https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses and, if you choose to license permissively, to Apache 2.0

**Comment by gkossakowski** [comment]
Thanks for raising this issue. I borrowed big swaths of code (e.g. Scala parser) from Dotty so I need to follow the same license.

**Comment by jvican** [comment]
Maybe it's too inconvenient, but I think you can use one license for that file and then choose another license for the rest of the project.

**Comment by gkossakowski** [comment]
Unfortunately, the parser code is not very well isolated in Dotty so I had to pull in more code, see: https://github.com/gkossakowski/kentuckymule/blob/master/notes.md#importing-dottys-parser

**Comment by fommil** [comment]
Being a pushover license, you can redistribute scalac code under whatever license you want, as long as you include the original text (which basically just says EPFL and Lightbend wrote some stuff).

**Comment by gkossakowski** [comment]
I'd be happy relicense under, e.g., Apache 2.0. Although, I'm not keen on learning details of mixing licenses. I'll take relicensing PRs with distilled wisdom on licensing.

**Comment by fommil** [comment]
My last comment pretty much sums it up. Practical steps are: 

1. Add the scala license as NOTICE, add your own name on the top and say "this project is Apache 2"
2. Add the Apache 2.0 license as LICENSE

Is not really appropriate for somebody to send a PR to do this, needs to be the copyright owner.

I gave a lightning talk on licensing. There are jokes and everything. http://fommil.github.io/scalasphere16/
